Module#3
Hakimbek/netflixroulette pull request #3
Opened 2022-11-30 10:48 UTC by Hakimbek

2022-12-04 12:36 UTC, MadinaNishanbaeva requested changes
We will use typescript please rewrite everything

after each approval from module 2 to the last module, pull requests should be merged into main and based on these changes, the following task is performed

2022-12-05 12:36 UTC, Hakimbek commented
Did I do everything right?

2022-12-06 05:06 UTC, MadinaNishanbaeva commented on .eslintrc.json
> +{
Where is your webpack?

2022-12-06 05:06 UTC, MadinaNishanbaeva commented on .eslintrc.json
> +  "rules": {}
Please, add the most recommended rules
```json
    "prettier/prettier": ["error", { "endOfLine": "auto" }],
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-explicit-any": "error",
    "@typescript-eslint/no-var-requires": "error",
    "@typescript-eslint/ban-ts-comment": "error",
    "no-console": "error"
```

2022-12-06 05:07 UTC, MadinaNishanbaeva commented on src/assets/movies/movies.ts
> +import avengers from "../images/avengers.png";
This file contains hardcoded data will be better store this file in mocked folder as well as these imported images

2022-12-06 05:07 UTC, MadinaNishanbaeva commented on src/components/App.tsx
> +      </ErrorBoundary>
What happens if an error occurs in the Header or Footer section?
You need to wrap the App component in <ErrorBoundary> and you need to do this in the index.tsx file

2022-12-06 05:07 UTC, MadinaNishanbaeva commented on src/components/Body/Body.tsx
> +import Sort from "./Sorting/Sort";
Let's try to give meaningful names

2022-12-06 05:07 UTC, MadinaNishanbaeva commented on src/components/Body/Body.tsx
> +function Body() {
The same with names
This component represents the whole page

2022-12-06 05:08 UTC, MadinaNishanbaeva commented on src/components/Body/MovieCards/MovieCards.tsx
> +  }
I have many questions about this component

Why are you using a class component?

Why are you specifying the type of props you are passing if you are not actually passing them?

2022-12-06 05:08 UTC, MadinaNishanbaeva commented on src/components/Body/MovieCards/MovieCards.tsx
> +            genre={movie.genre}
Why don't you pass all this data with one movie object?

```javascript
function MovieCards() {
  return (
    <div className={styles.movieCards}>
      {movies.map((movie) => (
        <MovieCard
          key={movie.id}
          movie={movie}
        />
      ))}
    </div>
  );
}
```
What do you think the component looks better now?

2022-12-06 05:08 UTC, MadinaNishanbaeva commented on src/components/Body/MovieCards/movieCards.types.ts
> +import React from "react";
Store all types in one folder called `types`

2022-12-06 05:09 UTC, MadinaNishanbaeva commented on src/components/Body/Sorting/SortByProperty/Property.tsx
> +function Property() {
What does this component? This name means nothing to me

2022-12-06 05:10 UTC, MadinaNishanbaeva commented on src/components/Header/Search/Text/Text.tsx
> +function Text() {
Components that are used in multiple places should be inside the common folder

The same with names

2022-12-06 05:10 UTC, MadinaNishanbaeva commented on src/components/Header/Search/Text/Text.tsx
> +  return <p className={styles.text}>FIND YOUR MOVIE</p>;
it would be better to use h1 here, and the text in uppercase... do it with css

2022-12-06 05:11 UTC, MadinaNishanbaeva commented on src/components/Header/Title/Title.tsx
> +function Title() {
The same with names

Title include button, I don't think it makes sense

2022-12-06 05:14 UTC, MadinaNishanbaeva requested changes
Each next task is based on the previous one, if the previous task was webpack and we agreed that we will use typescript, then both webpack and typescript should be used for the next task

2022-12-09 09:31 UTC, MadinaNishanbaeva commented on src/components/MovieCards/MovieCards.tsx
> +        <MovieCard key={Math.random()} movie={movie} />
Math.random() is very bad approach, don't use it please

2022-12-09 09:31 UTC, MadinaNishanbaeva commented on tsconfig.json
> +  "include": ["src", "mockData"],
mocked data should be inside of src folder

2022-12-09 09:31 UTC, MadinaNishanbaeva commented on webpack.common.js
>  const HtmlWebpackPlugin = require("html-webpack-plugin");
You need to make eslint ignore webpack.common.js file

2022-12-09 09:32 UTC, MadinaNishanbaeva approved these changes

2022-12-09 09:51 UTC, merged